# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BetterInstagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BetterInstagram
pod 'DateToolsSwift'
pod 'OneSignal', '>= 2.6.2', '< 3.0'
pod 'VBFPopFlatButton'
pod 'SwiftLocation', '~> 3.2.3'
pod 'YPImagePicker'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 5.0.0.beta.1'
pod 'LTMorphingLabel'
pod 'AwesomeTextFieldSwift'
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
